/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cursoqanovava;

import org.testng.annotations.Test;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    private void assertNotNull(String greeting, String string) {
    }
}
